### ISSUE TITLE
Spanish Translation Progress

### ISSUE THREAD

**Issue by laurelsilva** [typescript-cheatsheets/react-typescript-cheatsheet-es#2]
# 🚨 Please Read this before contributing

## Maintainer List

- @laurosilvacom 
- @dantehemerson
- @hlebon
- @carburo
- @aromanarguello 

## For New Translators

1. Check that no one else has claimed your page in the checklist and comments below. 
2. Comment below with the name of the cheatsheet you would like to translate.
3. Submit a PR, assign @laurosilvacom and add a link to it to your comment!
4. Please check the [style guide](https://github.com/typescript-cheatsheets/react-typescript-cheatsheet-es/blob/master/GUIA.md) to make sure translations are written in a consistent manner.

## Work in Progress

- [x] Translation Setup @laurosilvacom ✅
- [x] README.md @carburo ✅
- [x] ADVANCED.md @laurosilvacom  ✅
- [x] MIGRATING.md @dantehemerson ✅
- [x] HOC.md @hlebon ✅
- [x] CONTRIBUTORS.md @aromanarguello ✅

**Comment by hlebon** [comment]
Hi @laurosilvacom, I would love to translate the **HOC.md** page.

**Comment by dantehemerson** [comment]
Can I take `MIGRATING.md`?

**Comment by laurelsilva** [comment]
@dantehemerson @hlebon go for it! Fell free to move as a fast as you want, create a PR when you have it.

**Comment by carburo** [comment]
Hi @laurosilvacom, I would like to help with the Basic Guide (README.md)

**Comment by laurelsilva** [comment]
It's yours @carburo. Thanks for volunteering to help out!

**Comment by aromanarguello** [comment]
@laurosilvacom Hey Lauro! I can take the contributors.md :) !

**Comment by laurelsilva** [comment]
@aromanarguello you got it!

**Comment by aromanarguello** [comment]
@all-contributors please add laurosilvacom for Maintenance

**Comment by laurelsilva** [comment]
@dantehemerson @hlebon how's the translation going? Do you need any help?

**Comment by hlebon** [comment]
Hi @laurosilvacom, today I will be working on the Section 2: Excluding Props to finish the translation. Thanks.

**Comment by hlebon** [comment]
Hi @laurosilvacom, yesterday I created a PR.

**Comment by dantehemerson** [comment]
@laurosilvacom  please review my PR.
